import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          display: 'flex',
          flexDirection: 'column'
        }}
      >
        <div style={{
          height: 60,
        }}>
        </div>
        <div style={{
          display: 'flex',
        }}>
          <div style={{
            width: '200px'
          }}>
            <div>
              <Link
                className="rounded-base border-border bg-main text-main-foreground w500:text-sm inline-block border-2 px-3 py-1 text-base no-underline"
                href="/characters">
                Characters
              </Link>
            </div>
            <div>
              <Link href="/starships">
                Starships
              </Link>
            </div>
          </div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
