import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundColor: 'teal',
          display: 'flex',
          flexDirection: 'column'
        }}
      >
        <div style={{
          height: 60,
          backgroundColor: 'white'
        }}>
        </div>
        <div style={{
          display: 'flex',
        }}>
          <div style={{
            backgroundColor: 'white',
            color: 'teal',
            width: '200px'
          }}>
            <div>
              <Link href="/characters">
                Characters
              </Link>
            </div>
            <div>
              <Link href="/starships">
                Starships
              </Link>
            </div>
          </div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
